{{ if and .Values.aws.enabled .Values.aws.secretmanager.enabled }}
{{ $name :=  include "aws-xp-eso.name" . }}
{{ range .Values.aws.secretManager.secrets }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .name }}
  labels:
  {{- include "aws-xp-eso.labels" $ | nindent 4 }}
spec:
  secretStoreRef:
    name: {{ $name }}-aws-secretsmanager
    kind: SecretStore
  target:
    deletionPolicy: Delete
  data:
  {{- toYaml .data | nindent 4 }}
{{ end }} 
{{ end }}
