{{ if .Values.aws.enabled }}
{{ $name :=  include "aws-xp-eso.name" . }}
apiVersion: iam.aws.upbound.io/v1beta1
kind: RolePolicyAttachment
metadata:
  name: {{ .Values.aws.clusterName }}-{{ .Release.Namespace }}-{{ $name }}
  labels:
    {{- include "aws-xp-eso.labels" . | nindent 4 }}
spec:
  {{- with .Values.aws }}
  forProvider:
    policyArnSelector:
      matchLabels: 
        iam.aws.upbound.io/policy: {{ .clusterName }}-{{ $.Release.Namespace }}-{{ $name }}
    roleSelector:
      matchLabels: 
        iam.aws.upbound.io/role: {{ .clusterName }}-{{ $.Release.Namespace }}-{{ $name }}
  {{- end }}
{{ end }}
