{{ if and .Values.aws.enabled .Values.aws.secretmanager.enabled }}
{{ $name :=  include "aws-xp-eso.name" . }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ $name }}-aws-secretsmanager
  labels:
  {{- include "aws-xp-eso.labels" . | nindent 4 }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.aws.region }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ include "aws-xp-eso.serviceAccountName" . }}
{{ end }}
