{{ if .Values.serviceAccount.create }}
{{ $name :=  include "aws-xp-eso.name" . }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aws-xp-eso.serviceAccountName" . }}
  annotations:
  {{- if .Values.aws.enabled }}
    {{- with .Values.aws }}
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .accountId }}:role/{{ .clusterName }}-{{ $.Release.Namespace }}-{{ $name }}
    {{- end }}
  {{- else }}
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
  {{- end }}
  labels:
    {{- include "aws-xp-eso.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{ end }}
